import type { User, Complaint, Task, Idea, Event, Announcement, Notification, Training, ChatMessage } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'أحمد محمد الحسن',
    email: 'president@agr-homs.edu.sy',
    role: 'president',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmed',
    phone: '0944123456',
    isActive: true,
    joinDate: '2024-09-01',
    permissions: ['all'],
  },
  {
    id: '2',
    name: 'سارة خالد الرحمون',
    email: 'vp@agr-homs.edu.sy',
    role: 'vice_president',
    office: 'organization',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sara',
    phone: '0944234567',
    isActive: true,
    joinDate: '2024-09-01',
    permissions: ['manage_complaints', 'manage_tasks', 'view_reports'],
  },
  {
    id: '3',
    name: 'محمد علي سليمان',
    email: 'events@agr-homs.edu.sy',
    role: 'office_head',
    office: 'events',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mohammed',
    phone: '0944345678',
    isActive: true,
    joinDate: '2024-09-05',
    permissions: ['manage_events', 'manage_members'],
  },
  {
    id: '4',
    name: 'ريم الصالح',
    email: 'media@agr-homs.edu.sy',
    role: 'office_head',
    office: 'media',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=reem',
    phone: '0944456789',
    isActive: true,
    joinDate: '2024-09-05',
  },
  {
    id: '5',
    name: 'عمر حسين عبيدو',
    email: 'member1@agr-homs.edu.sy',
    role: 'member',
    office: 'events',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=omar',
    isActive: true,
    joinDate: '2024-09-10',
  },
  {
    id: '6',
    name: 'طالب',
    email: 'student@agr-homs.edu.sy',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student',
    isActive: true,
    joinDate: '2024-10-01',
  },
];

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: 'C001',
    title: 'انقطاع الانترنت في قاعة المكتبة',
    description: 'منذ أسبوع وخدمة الإنترنت منقطعة في قاعة المكتبة مما يعيق الدراسة والبحث العلمي',
    type: 'بنية تحتية',
    status: 'processing',
    location: 'المكتبة',
    submitterName: 'طالب مجهول',
    createdAt: '2026-03-28T10:30:00',
    updatedAt: '2026-03-29T09:00:00',
    assignedTo: '3',
  },
  {
    id: 'C002',
    title: 'مشكلة في جدول المحاضرات',
    description: 'يوجد تعارض في مواعيد المحاضرات للفصل الثاني مما يسبب ارباكاً للطلاب',
    type: 'أكاديمي',
    status: 'new',
    submitterName: 'محمد السليمان',
    submitterPhone: '0912345678',
    createdAt: '2026-03-30T14:20:00',
    updatedAt: '2026-03-30T14:20:00',
  },
  {
    id: 'C003',
    title: 'نظافة المدرج الرئيسي',
    description: 'المدرج الرئيسي يحتاج لتنظيف فوري خاصة بعد الامتحانات',
    type: 'خدمات',
    status: 'solved',
    location: 'المدرج الرئيسي',
    createdAt: '2026-03-25T09:00:00',
    updatedAt: '2026-03-27T16:00:00',
    response: 'تم التنسيق مع الجهات المعنية وتنظيف المدرج',
  },
  {
    id: 'C004',
    title: 'طلب مصلى للطلاب',
    description: 'يطلب الطلاب توفير مكان مخصص للصلاة قريب من قاعات الدراسة',
    type: 'مرافق',
    status: 'transferred',
    createdAt: '2026-03-20T11:00:00',
    updatedAt: '2026-03-22T10:00:00',
    assignedTo: '2',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'T001',
    title: 'تنظيم حفل افتتاح السنة الدراسية',
    description: 'التخطيط والتنسيق لإقامة حفل افتتاح رسمي للسنة الدراسية الجديدة',
    status: 'in_progress',
    priority: 'high',
    office: 'events',
    assignedTo: 'محمد علي سليمان',
    dueDate: '2026-04-15',
    createdAt: '2026-03-20',
    createdBy: 'أحمد محمد الحسن',
    completionRate: 65,
    tags: ['فعاليات', 'أولوية عالية'],
  },
  {
    id: 'T002',
    title: 'إعداد التقرير الشهري لمكتب الإعلام',
    description: 'جمع وتوثيق جميع الأنشطة الإعلامية خلال شهر مارس',
    status: 'review',
    priority: 'medium',
    office: 'media',
    assignedTo: 'ريم الصالح',
    dueDate: '2026-04-05',
    createdAt: '2026-03-25',
    createdBy: 'سارة خالد الرحمون',
    completionRate: 90,
    tags: ['تقارير', 'إعلام'],
  },
  {
    id: 'T003',
    title: 'دورة تدريبية في مهارات القيادة',
    description: 'تنظيم دورة تدريبية لأعضاء الهيئة حول مهارات القيادة والتنظيم',
    status: 'new',
    priority: 'medium',
    office: 'training',
    assignedTo: 'عمر حسين عبيدو',
    dueDate: '2026-04-30',
    createdAt: '2026-04-01',
    createdBy: 'أحمد محمد الحسن',
    completionRate: 0,
    tags: ['تدريب'],
  },
  {
    id: 'T004',
    title: 'استطلاع رأي الطلاب حول الخدمات',
    description: 'إعداد وتوزيع استبيان لمعرفة مدى رضا الطلاب عن خدمات الهيئة',
    status: 'late',
    priority: 'urgent',
    office: 'follow_up',
    assignedTo: 'سارة خالد الرحمون',
    dueDate: '2026-03-28',
    createdAt: '2026-03-15',
    createdBy: 'أحمد محمد الحسن',
    completionRate: 30,
    tags: ['متابعة', 'طلاب'],
  },
  {
    id: 'T005',
    title: 'تحديث صفحة التواصل الاجتماعي',
    description: 'نشر محتوى منتظم ومتنوع على قنوات التواصل الاجتماعي للهيئة',
    status: 'completed',
    priority: 'low',
    office: 'media',
    assignedTo: 'ريم الصالح',
    dueDate: '2026-03-31',
    createdAt: '2026-03-01',
    createdBy: 'سارة خالد الرحمون',
    completionRate: 100,
    tags: ['إعلام', 'سوشيال ميديا'],
  },
];

export const MOCK_IDEAS: Idea[] = [
  {
    id: 'I001',
    title: 'إنشاء مختبر زراعي للطلاب',
    description: 'اقتراح إنشاء مختبر متخصص للطلاب لإجراء التجارب الزراعية والبحوث العلمية بشكل أكثر احترافية',
    category: 'أكاديمي',
    status: 'studying',
    votes: 47,
    comments: [
      { id: 'c1', text: 'فكرة ممتازة! هذا سيساعد الطلاب كثيراً', author: 'أحمد م.', createdAt: '2026-03-20' },
      { id: 'c2', text: 'أتمنى تنفيذها في القريب العاجل', author: 'سارة ر.', createdAt: '2026-03-22' },
    ],
    submittedBy: 'طالب مجهول',
    isAnonymous: true,
    createdAt: '2026-03-15',
    hasVoted: false,
  },
  {
    id: 'I002',
    title: 'برنامج إرشاد أكاديمي للطلاب الجدد',
    description: 'تأسيس برنامج حيث يقوم الطلاب المتقدمون بإرشاد وتوجيه الطلاب المستجدين',
    category: 'تنظيمي',
    status: 'in_progress',
    votes: 38,
    comments: [
      { id: 'c3', text: 'بدأنا بالتخطيط لهذا البرنامج', author: 'الهيئة', createdAt: '2026-03-25' },
    ],
    submittedBy: 'محمد السليمان',
    isAnonymous: false,
    createdAt: '2026-03-10',
    hasVoted: true,
  },
  {
    id: 'I003',
    title: 'مهرجان زراعي سنوي',
    description: 'تنظيم مهرجان سنوي يعرض فيه الطلاب مشاريعهم الزراعية ويتنافسون على جوائز قيّمة',
    category: 'فعاليات',
    status: 'pending',
    votes: 62,
    comments: [],
    submittedBy: 'ريم الأحمد',
    isAnonymous: false,
    createdAt: '2026-04-01',
    hasVoted: false,
  },
  {
    id: 'I004',
    title: 'منصة تبادل الكتب الدراسية',
    description: 'موقع أو تطبيق يتيح للطلاب تبادل وبيع الكتب الدراسية فيما بينهم بأسعار معقولة',
    category: 'تقني',
    status: 'completed',
    votes: 55,
    comments: [
      { id: 'c4', text: 'تم تنفيذها بنجاح!', author: 'مكتب التقنية', createdAt: '2026-03-28' },
    ],
    submittedBy: 'عمر المصري',
    isAnonymous: false,
    createdAt: '2026-02-20',
    hasVoted: false,
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: 'E001',
    title: 'ملتقى الخريجين الزراعيين',
    description: 'لقاء سنوي يجمع طلاب الكلية بخريجيها البارزين لتبادل الخبرات والفرص المهنية',
    date: '2026-04-20T10:00:00',
    location: 'قاعة المؤتمرات الكبرى',
    capacity: 200,
    registeredCount: 145,
    status: 'upcoming',
    organizer: 'مكتب الفعاليات',
    tags: ['تواصل', 'مهني'],
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&q=80',
  },
  {
    id: 'E002',
    title: 'ورشة عمل: الزراعة الذكية والتكنولوجيا',
    description: 'ورشة عمل متخصصة حول تطبيقات التكنولوجيا الحديثة في المجال الزراعي',
    date: '2026-04-12T09:00:00',
    location: 'مختبر الحاسوب - البناء ج',
    capacity: 50,
    registeredCount: 50,
    status: 'upcoming',
    organizer: 'مكتب التدريب',
    tags: ['تكنولوجيا', 'زراعة ذكية'],
    image: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400&q=80',
  },
  {
    id: 'E003',
    title: 'يوم البيئة الزراعية',
    description: 'فعالية خارجية للتوعية البيئية وزرع الأشجار في محيط الكلية',
    date: '2026-03-21T08:00:00',
    location: 'الحديقة المركزية',
    capacity: 150,
    registeredCount: 130,
    status: 'completed',
    organizer: 'مكتب الفعاليات',
    tags: ['بيئة', 'تشجير'],
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
  },
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'A001',
    title: 'إعلان هام: فتح باب التسجيل لدورات الفصل الربيعي',
    content: 'تعلن الهيئة الطلابية عن فتح باب التسجيل للدورات التدريبية للفصل الربيعي 2026. تشمل الدورات: مهارات البحث العلمي، إدارة المشاريع، والبرمجة الزراعية.',
    type: 'announcement',
    publishedAt: '2026-04-01T10:00:00',
    author: 'الهيئة الطلابية',
    isPinned: true,
  },
  {
    id: 'A002',
    title: 'نتائج انتخابات الهيئة الطلابية 2025-2026',
    content: 'تعلن إدارة الكلية عن نتائج انتخابات الهيئة الطلابية وتهنئ الفائزين بثقة زملائهم الطلاب.',
    type: 'news',
    publishedAt: '2026-03-28T14:00:00',
    author: 'إدارة الكلية',
    isPinned: false,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
  },
  {
    id: 'A003',
    title: 'تنبيه: تغيير موعد الامتحانات النصفية',
    content: 'تم تغيير موعد الامتحانات النصفية إلى الأسبوع الثامن بدلاً من السابع. يرجى الاطلاع على الجدول المعدل.',
    type: 'alert',
    publishedAt: '2026-03-30T09:00:00',
    author: 'شؤون الطلاب',
    isPinned: true,
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'N001',
    title: 'مهمة جديدة',
    message: 'تم تعيينك على مهمة "تنظيم حفل الافتتاح"',
    type: 'task',
    isRead: false,
    createdAt: '2026-04-02T09:00:00',
  },
  {
    id: 'N002',
    title: 'شكوى جديدة',
    message: 'شكوى جديدة: "مشكلة في جدول المحاضرات" تنتظر المعالجة',
    type: 'complaint',
    isRead: false,
    createdAt: '2026-04-02T10:30:00',
  },
  {
    id: 'N003',
    title: 'فكرة جديدة',
    message: 'فكرة "مهرجان زراعي سنوي" حصلت على 62 تصويتاً',
    type: 'idea',
    isRead: true,
    createdAt: '2026-04-01T16:00:00',
  },
  {
    id: 'N004',
    title: 'فعالية قادمة',
    message: 'تذكير: ملتقى الخريجين بعد 18 يوماً',
    type: 'event',
    isRead: false,
    createdAt: '2026-04-02T08:00:00',
  },
];

export const MOCK_TRAINING: Training[] = [
  {
    id: 'TR001',
    title: 'مهارات القيادة والإدارة',
    description: 'دورة متخصصة في مهارات القيادة الفعّالة وإدارة الفرق',
    trainer: 'د. سامر الحسن',
    startDate: '2026-04-10',
    endDate: '2026-04-14',
    capacity: 30,
    registeredCount: 22,
    category: 'قيادة',
    level: 'intermediate',
    status: 'upcoming',
  },
  {
    id: 'TR002',
    title: 'أساسيات التصميم الجرافيكي',
    description: 'تعلم أدوات التصميم الحديثة لإنتاج محتوى بصري احترافي',
    trainer: 'م. رنا الجمال',
    startDate: '2026-04-20',
    endDate: '2026-04-24',
    capacity: 25,
    registeredCount: 25,
    category: 'إعلام',
    level: 'beginner',
    status: 'upcoming',
  },
];

export const MOCK_MESSAGES: ChatMessage[] = [
  {
    id: 'M001',
    text: 'السلام عليكم، نذكر الجميع باجتماع مكتب الفعاليات غداً الساعة 3 عصراً',
    sender: 'محمد علي سليمان',
    senderId: '3',
    createdAt: '2026-04-02T09:00:00',
    room: 'general',
    isPinned: true,
  },
  {
    id: 'M002',
    text: 'وعليكم السلام، تمام سنكون حاضرين',
    sender: 'عمر حسين عبيدو',
    senderId: '5',
    createdAt: '2026-04-02T09:15:00',
    room: 'general',
  },
  {
    id: 'M003',
    text: 'هل اكتمل تقرير شهر مارس؟ ننتظر تسليمه اليوم',
    sender: 'سارة خالد الرحمون',
    senderId: '2',
    createdAt: '2026-04-02T10:00:00',
    room: 'general',
  },
  {
    id: 'M004',
    text: 'نعم، التقرير جاهز وسيتم رفعه قبل المساء',
    sender: 'ريم الصالح',
    senderId: '4',
    createdAt: '2026-04-02T10:30:00',
    room: 'general',
  },
];

export const OFFICES: Record<string, string> = {
  organization: 'مكتب التنظيم',
  follow_up: 'مكتب المتابعة',
  media: 'مكتب الإعلام',
  events: 'مكتب الفعاليات',
  training: 'مكتب التدريب',
};

export const ROLES: Record<string, string> = {
  president: 'رئيس الهيئة',
  vice_president: 'نائب الرئيس',
  office_head: 'رئيس مكتب',
  member: 'عضو',
  student: 'طالب',
};

export const COMPLAINT_TYPES = [
  'بنية تحتية', 'أكاديمي', 'خدمات', 'مرافق', 'إداري', 'اجتماعي', 'أخرى'
];

export const IDEA_CATEGORIES = [
  'تقني', 'تنظيمي', 'فعاليات', 'تدريب', 'أكاديمي', 'بيئي', 'اجتماعي', 'أخرى'
];

export const QR_LOCATIONS = [
  { id: 'main', name: 'المبنى الرئيسي' },
  { id: 'library', name: 'المكتبة' },
  { id: 'lab', name: 'المختبرات' },
  { id: 'cafeteria', name: 'الكافتيريا' },
  { id: 'sports', name: 'الملاعب الرياضية' },
  { id: 'admin', name: 'الإدارة' },
];
